
version: '3.1'
services: 
    php-apache:
        environment:
            WEB_DOCUMENT_ROOT: /var/www/html
        container_name: roundbob
        build: ./docker
        ports: 
            - 8080:80
        volumes:
            - .:/var/www
    mysql: 
        container_name: db
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ~/db/mysql/data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root,